/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SurveyReward {
  export type CompletionProofStruct = {
    respondent: AddressLike;
    surveyId: BigNumberish;
    answerHash: BytesLike;
    rewardAmount: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type CompletionProofStructOutput = [
    respondent: string,
    surveyId: bigint,
    answerHash: string,
    rewardAmount: bigint,
    nonce: bigint,
    deadline: bigint
  ] & {
    respondent: string;
    surveyId: bigint;
    answerHash: string;
    rewardAmount: bigint;
    nonce: bigint;
    deadline: bigint;
  };
}

export interface SurveyRewardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CREATOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "VALIDATOR_ROLE"
      | "VERIFIER_ROLE"
      | "approveVerification"
      | "claimRewards"
      | "claimableRewards"
      | "closeSurvey"
      | "createSurvey"
      | "eip712Domain"
      | "getCompletionProofDigest"
      | "getRoleAdmin"
      | "grantCreatorRole"
      | "grantRole"
      | "hasRole"
      | "hasSubmittedSurveyResponse"
      | "isVerified"
      | "pause"
      | "paused"
      | "rejectVerification"
      | "renounceRole"
      | "requestVerification"
      | "revokeCreatorRole"
      | "revokeRole"
      | "revokeVerification"
      | "submitResponseWithProof"
      | "supportsInterface"
      | "surveyCount"
      | "surveys"
      | "totalEarned"
      | "unpause"
      | "usedProofNonces"
      | "verificationProofHash"
      | "verificationStatus"
      | "withdrawUnusedRewards"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorRoleGranted"
      | "CreatorRoleRevoked"
      | "EIP712DomainChanged"
      | "Paused"
      | "ResponseSubmitted"
      | "RewardsClaimed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SurveyClosed"
      | "SurveyCreated"
      | "Unpaused"
      | "UnusedRewardsWithdrawn"
      | "VerificationApproved"
      | "VerificationRejected"
      | "VerificationRequested"
      | "VerificationRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveVerification",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSurvey",
    values: [string, string, string, string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompletionProofDigest",
    values: [SurveyReward.CompletionProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCreatorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmittedSurveyResponse",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectVerification",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCreatorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVerification",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponseWithProof",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "surveyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surveys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usedProofNonces",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationProofHash",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnusedRewards",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompletionProofDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCreatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmittedSurveyResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCreatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponseWithProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "surveys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedProofNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationProofHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnusedRewards",
    data: BytesLike
  ): Result;
}

export namespace CreatorRoleGrantedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorRoleRevokedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    respondent: AddressLike,
    answerHash: BytesLike,
    rewardAmount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    respondent: string,
    answerHash: string,
    rewardAmount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    respondent: string;
    answerHash: string;
    rewardAmount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [respondent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [respondent: string, amount: bigint];
  export interface OutputObject {
    respondent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyClosedEvent {
  export type InputTuple = [surveyId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [surveyId: bigint, creator: string];
  export interface OutputObject {
    surveyId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyCreatedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    creator: AddressLike,
    rewardPerResponse: BigNumberish,
    maxResponses: BigNumberish,
    escrowAmount: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    creator: string,
    rewardPerResponse: bigint,
    maxResponses: bigint,
    escrowAmount: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    creator: string;
    rewardPerResponse: bigint;
    maxResponses: bigint;
    escrowAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnusedRewardsWithdrawnEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [surveyId: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    surveyId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationApprovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRejectedEvent {
  export type InputTuple = [wallet: AddressLike, reason: string];
  export type OutputTuple = [wallet: string, reason: string];
  export interface OutputObject {
    wallet: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [wallet: AddressLike, proofHash: BytesLike];
  export type OutputTuple = [wallet: string, proofHash: string];
  export interface OutputObject {
    wallet: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRevokedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SurveyReward extends BaseContract {
  connect(runner?: ContractRunner | null): SurveyReward;
  waitForDeployment(): Promise<this>;

  interface: SurveyRewardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CREATOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  VALIDATOR_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  approveVerification: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimableRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  closeSurvey: TypedContractMethod<
    [surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSurvey: TypedContractMethod<
    [
      title: string,
      description: string,
      question: string,
      options: string[],
      rewardPerResponse: BigNumberish,
      maxResponses: BigNumberish
    ],
    [void],
    "payable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getCompletionProofDigest: TypedContractMethod<
    [proof: SurveyReward.CompletionProofStruct],
    [string],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantCreatorRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasSubmittedSurveyResponse: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isVerified: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rejectVerification: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestVerification: TypedContractMethod<
    [kycProofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeCreatorRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeVerification: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResponseWithProof: TypedContractMethod<
    [
      surveyId: BigNumberish,
      answerHash: BytesLike,
      rewardAmount: BigNumberish,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  surveyCount: TypedContractMethod<[], [bigint], "view">;

  surveys: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        title: string;
        description: string;
        question: string;
        rewardPerResponse: bigint;
        maxResponses: bigint;
        responseCount: bigint;
        escrowRemaining: bigint;
        active: boolean;
        unusedRewardsWithdrawn: boolean;
      }
    ],
    "view"
  >;

  totalEarned: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usedProofNonces: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  verificationProofHash: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  verificationStatus: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  withdrawUnusedRewards: TypedContractMethod<
    [surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CREATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveVerification"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "closeSurvey"
  ): TypedContractMethod<[surveyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSurvey"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      question: string,
      options: string[],
      rewardPerResponse: BigNumberish,
      maxResponses: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCompletionProofDigest"
  ): TypedContractMethod<
    [proof: SurveyReward.CompletionProofStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantCreatorRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmittedSurveyResponse"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rejectVerification"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<[kycProofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCreatorRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeVerification"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResponseWithProof"
  ): TypedContractMethod<
    [
      surveyId: BigNumberish,
      answerHash: BytesLike,
      rewardAmount: BigNumberish,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "surveyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "surveys"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        creator: string;
        title: string;
        description: string;
        question: string;
        rewardPerResponse: bigint;
        maxResponses: bigint;
        responseCount: bigint;
        escrowRemaining: bigint;
        active: boolean;
        unusedRewardsWithdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedProofNonces"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "verificationProofHash"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "verificationStatus"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawUnusedRewards"
  ): TypedContractMethod<[surveyId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CreatorRoleGranted"
  ): TypedContractEvent<
    CreatorRoleGrantedEvent.InputTuple,
    CreatorRoleGrantedEvent.OutputTuple,
    CreatorRoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorRoleRevoked"
  ): TypedContractEvent<
    CreatorRoleRevokedEvent.InputTuple,
    CreatorRoleRevokedEvent.OutputTuple,
    CreatorRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyClosed"
  ): TypedContractEvent<
    SurveyClosedEvent.InputTuple,
    SurveyClosedEvent.OutputTuple,
    SurveyClosedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyCreated"
  ): TypedContractEvent<
    SurveyCreatedEvent.InputTuple,
    SurveyCreatedEvent.OutputTuple,
    SurveyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UnusedRewardsWithdrawn"
  ): TypedContractEvent<
    UnusedRewardsWithdrawnEvent.InputTuple,
    UnusedRewardsWithdrawnEvent.OutputTuple,
    UnusedRewardsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "VerificationApproved"
  ): TypedContractEvent<
    VerificationApprovedEvent.InputTuple,
    VerificationApprovedEvent.OutputTuple,
    VerificationApprovedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRejected"
  ): TypedContractEvent<
    VerificationRejectedEvent.InputTuple,
    VerificationRejectedEvent.OutputTuple,
    VerificationRejectedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRevoked"
  ): TypedContractEvent<
    VerificationRevokedEvent.InputTuple,
    VerificationRevokedEvent.OutputTuple,
    VerificationRevokedEvent.OutputObject
  >;

  filters: {
    "CreatorRoleGranted(address)": TypedContractEvent<
      CreatorRoleGrantedEvent.InputTuple,
      CreatorRoleGrantedEvent.OutputTuple,
      CreatorRoleGrantedEvent.OutputObject
    >;
    CreatorRoleGranted: TypedContractEvent<
      CreatorRoleGrantedEvent.InputTuple,
      CreatorRoleGrantedEvent.OutputTuple,
      CreatorRoleGrantedEvent.OutputObject
    >;

    "CreatorRoleRevoked(address)": TypedContractEvent<
      CreatorRoleRevokedEvent.InputTuple,
      CreatorRoleRevokedEvent.OutputTuple,
      CreatorRoleRevokedEvent.OutputObject
    >;
    CreatorRoleRevoked: TypedContractEvent<
      CreatorRoleRevokedEvent.InputTuple,
      CreatorRoleRevokedEvent.OutputTuple,
      CreatorRoleRevokedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ResponseSubmitted(uint256,address,bytes32,uint256,uint256)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SurveyClosed(uint256,address)": TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;
    SurveyClosed: TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;

    "SurveyCreated(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
    SurveyCreated: TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UnusedRewardsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      UnusedRewardsWithdrawnEvent.InputTuple,
      UnusedRewardsWithdrawnEvent.OutputTuple,
      UnusedRewardsWithdrawnEvent.OutputObject
    >;
    UnusedRewardsWithdrawn: TypedContractEvent<
      UnusedRewardsWithdrawnEvent.InputTuple,
      UnusedRewardsWithdrawnEvent.OutputTuple,
      UnusedRewardsWithdrawnEvent.OutputObject
    >;

    "VerificationApproved(address)": TypedContractEvent<
      VerificationApprovedEvent.InputTuple,
      VerificationApprovedEvent.OutputTuple,
      VerificationApprovedEvent.OutputObject
    >;
    VerificationApproved: TypedContractEvent<
      VerificationApprovedEvent.InputTuple,
      VerificationApprovedEvent.OutputTuple,
      VerificationApprovedEvent.OutputObject
    >;

    "VerificationRejected(address,string)": TypedContractEvent<
      VerificationRejectedEvent.InputTuple,
      VerificationRejectedEvent.OutputTuple,
      VerificationRejectedEvent.OutputObject
    >;
    VerificationRejected: TypedContractEvent<
      VerificationRejectedEvent.InputTuple,
      VerificationRejectedEvent.OutputTuple,
      VerificationRejectedEvent.OutputObject
    >;

    "VerificationRequested(address,bytes32)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;

    "VerificationRevoked(address)": TypedContractEvent<
      VerificationRevokedEvent.InputTuple,
      VerificationRevokedEvent.OutputTuple,
      VerificationRevokedEvent.OutputObject
    >;
    VerificationRevoked: TypedContractEvent<
      VerificationRevokedEvent.InputTuple,
      VerificationRevokedEvent.OutputTuple,
      VerificationRevokedEvent.OutputObject
    >;
  };
}
